Refactoring des shells et ajout code erreur dans log de repec-mirror-archive.
L'objectif du refactoring est de rendre le code un peu plus portable
(Linux/MacOS X).

diff --git a/bin/md2beamer b/bin/md2beamer
--- a/bin/md2beamer
+++ b/bin/md2beamer
@@ -16,7 +16,7 @@
 #
 #     -h, --help           affiche ce message d'aide
 #     -t, --theme THEME    utilise THEME pour la forme du diaporama au lieu de
-#                          lille1. list permet de lister les thèmes. 
+#                          lille1. 'list' permet de lister les thèmes.
 #     -s, --slide-level N  spéficie le niveau de titre qui définit une diapo
 #                          au lieu du niveau 2
 #     -L, --latex          produit le source LaTeX plutôt que le résultat PDF
@@ -33,6 +33,17 @@
 # Convertir le fichier presentation.md qui inclut l'image image.pdf
 #
 #     md2beamer presentation.md image.pdf
+#
+# DEPENDANCES
+#
+# Pour fonctionner md2beamer a besoin que 'pandoc' ainsi qu'une installation
+# TeX (avec 'pdflatex' et la classe 'beamer.cls') soit accessible. Seul la
+# distribution TeXLive disponible pour Unix (sous le nom MacTeX pour Mac OS X)
+# a été testée.
+#
+# [pandoc]: http://pandoc.org
+# [texlive]: http://tug.org/texlive
+# [mactex]: http://tug.org/mactex
 #
 # DETAILS TECHNIQUES
 #
@@ -53,7 +64,6 @@
 # généralement c'est cat (quand le contenu est textuel et qu'il faut juste
 # l'extraire) ou base64 --decode (quand le contenu du fichier est binaire et
 # qu'on l'a embarqué en base64).
-#
 
 # FIXME: SOURCE et FICHIERS-INCLUS devraient pouvoir être un chemin quelconque (absolu par exemple)
 
@@ -66,11 +76,11 @@ else
 fi
 
 doc () { sed -n '2,/^$/ { s/^ *#// ; s/^ //g ; t ok ; d ; :ok ; p }' <$0 ; }
-err () { echo "$(basename $0): error: $*" 1>&2 ; exit 1 ; }
-log () { date "+%F %T $(basename $0) $*" | tee -a "$LOG" ; }
-abs () { echo $(cd $(dirname $1) ; pwd)/$(basename $1) ; }
+die () { echo "${0##*/}: error: $*" 1>&2 ; exit 1 ; }
+log () { date "+%F %T ${0##*/} $*" | tee -a "$LOG" ; }
+abs () { echo $(cd $(dirname $1) ; pwd)/${1##*/} ; }
 mute () { 1>/dev/null 2>&1 $* ; }
-need () { err "$1 is unavailable" ; }
+need () { die "$1 is unavailable" ; }
 
 # réussit si les outils nécessaires sont accessibles
 check ()
@@ -146,9 +156,9 @@ do
     shift
 done
 
-check || err "needed tools missing"
+check || die "needed tools missing"
 
-[ -z $1 ] && err "missing source file"
+[ -z $1 ] && die "missing source file"
 SRC=$(abs $1)
 dsttex=$(basename $1 .md).tex
 dstpdf=$(basename $1 .md).pdf
diff --git a/bin/repec b/bin/repec
--- a/bin/repec
+++ b/bin/repec
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 # Outils de manipulation de la base RePEc
 #
 # usage: repec [-h|--help] COMMANDE [ARGS...]
@@ -10,20 +10,28 @@
 BIN="$(cd $(dirname $0) ; pwd)"
 CMD="$(basename $0)"
 
-usage ()
+die () { echo "${0##*/}: error: $*" 1>&2 ; exit 1 ; }
+
+doc ()
 {
-    SUB=$(cd "$BIN" && ls "$CMD-"* 2>/dev/null | sed "s/^$CMD-//g")
-    sed -n '2,/^$/ { s/^ *#// ; s/^ //g ; t ok ; d ; :ok ; p }' <$0
-    [ -z "$SUB" ] || for s in $SUB
-    do
-        printf "\t$s\t\t$(sed -n '2 { s/^ *# // ; p }' $BIN/$CMD-$s)\n"
-    done
+  sed -n '2,/^$/ { s/^ *#// ; s/^ //g ; t ok ; d ; :ok ; p }' <$0
+
+  SUB=$(cd "$BIN" && ls "$CMD-"* 2>/dev/null | sed "s/^$CMD-//g")
+  [ -z "$SUB" ] || for s in $SUB
+  do
+    printf "  %-20s $(sed -n '2 { s/^ *# // ; p }' $BIN/$CMD-$s)\n" "$s"
+  done
 }
 
-[ "x$1" = "x-h" -o "x$1" = "x--help" ] && usage && exit
-[ $# -lt 1 ] && exit 1
+[ "x$1" = "x-h" -o "x$1" = "x--help" ] && doc && exit
+[ $# -lt 1 ] && die "bad syntax. Try --help."
 
 CMD="$CMD-$1"
 shift
-[ ! -x "$BIN/$CMD" ] && exit 1
+[ ! -x "$BIN/$CMD" ] && die "unknown command $CMD"
 exec "$BIN/$CMD" "$@"
+
+# Local Variables:
+# sh-indentation: 2
+# sh-basic-offset: 2
+# End:
